use crate::corpus::TOPICS;
use crate::metrics::{BenchTimings, StrategyReport, MAX_INDEX_BUILD_TIME, MAX_QUERY_P95};

pub(crate) fn render_report(
    reports: &[StrategyReport],
    n_queries: usize,
    n_sessions: usize,
    noise_sessions: usize,
    timings: &BenchTimings,
) -> String {
    let mut out = String::new();
    out.push_str("# Search Recall Bench\n\n");
    out.push_str("Generated by `cargo test --test recall_bench`. See ");
    out.push_str("[`tests/recall_bench.rs`](../tests/recall_bench.rs) for the harness ");
    out.push_str("and [`tests/fixtures/bench_recall/queries.json`](../tests/fixtures/bench_recall/queries.json) ");
    out.push_str("for the labeled query set.\n\n");
    out.push_str(&format!(
        "Corpus: {n_sessions} synthetic sessions ({topic_count} labeled Claude-format topics + {noise_sessions} mixed-provider distractors), 4 messages each.\n",
        topic_count = TOPICS.len(),
    ));
    out.push_str(&format!("Query set: {n_queries} labeled queries.\n\n"));

    out.push_str("## Overall\n\n");
    out.push_str("| Strategy | Recall@10 | MRR |\n");
    out.push_str("|---|---:|---:|\n");
    for r in reports {
        out.push_str(&format!(
            "| {} | {:.3} | {:.3} |\n",
            r.strategy,
            r.overall.recall(),
            r.overall.mrr(),
        ));
    }

    let mut tags: Vec<String> = reports
        .iter()
        .flat_map(|r| r.per_tag.keys().cloned())
        .collect();
    tags.sort();
    tags.dedup();

    if !tags.is_empty() {
        out.push_str("\n## By query type\n\n");
        out.push_str("| Strategy | Tag | Recall@10 | MRR |\n");
        out.push_str("|---|---|---:|---:|\n");
        for r in reports {
            for tag in &tags {
                if let Some(m) = r.per_tag.get(tag) {
                    out.push_str(&format!(
                        "| {} | {} | {:.3} | {:.3} |\n",
                        r.strategy,
                        tag,
                        m.recall(),
                        m.mrr(),
                    ));
                }
            }
        }
    }

    out.push_str("\n## Latency Gates\n\n");
    out.push_str("| Measurement | Value | Gate |\n");
    out.push_str("|---|---:|---:|\n");
    out.push_str(&format!(
        "| Index build | {} ms | <= {} ms |\n",
        timings.index_build.as_millis(),
        MAX_INDEX_BUILD_TIME.as_millis(),
    ));
    out.push_str(&format!(
        "| Query p95 | {} ms | <= {} ms |\n",
        timings.query_p95.as_millis(),
        MAX_QUERY_P95.as_millis(),
    ));

    out.push_str("\n## Methodology notes\n\n");
    out.push_str("- **lexical** is the production Tantivy BM25 index (`SearchIndex::search`).\n");
    out.push_str(
        "- **semantic** is a deterministic hashed-bag-of-words IDF cosine ranker baked into the ",
    );
    out.push_str(
        "harness — *not* the production fastembed/MiniLM embedder. It exists so the bench ",
    );
    out.push_str(
        "runs in CI without network and so the hybrid row has a non-trivial second signal. ",
    );
    out.push_str("Swap `SemanticRanker` for the production embedder when comparing against real FastEmbed output.\n");
    out.push_str("- **hybrid** = Reciprocal Rank Fusion of the two lists, k = 60.\n");
    out.push_str("- recall@10 = fraction of queries whose target is in the top 10.\n");
    out.push_str(
        "- MRR = mean of 1/rank for each query (rank counted from 1; 0 if outside top 10).\n",
    );
    out.push_str(
        "- Query tags: `lexical` queries have the target's exact terms; `semantic` queries ",
    );
    out.push_str(
        "use paraphrases. The breakdown surfaces where each strategy actually earns its keep.\n",
    );

    out
}
